### ISSUE TITLE
Interactors x RxJava

### ISSUE THREAD

**Issue by cavarzan** [antoniolg/Bandhook-Kotlin#10]
Hi!

This isn't a issue, but it's more like some doubt.

The Interactor pattern is quite simular to the Command pattern, just returning some Event instead of being void and didn't support undo like we saw in design pattern books. In this case, it is wrong to create a second method to call if we have a presenter with 2 or more calls - e.g creating some action in DetailsActivity - to Interactors?

In bandhook the Thread Executor is from Path, which I cannot see working with RxJava. Those executors can be used with RxJava (I tried to accomplish that but without success)? I'm thinking to create some structure that the Interactor will return an Observable instead of some Event (I use this in normal Java development, but not Kotlin until now). If you think that this can be useful, I can made a PR to the project with this second approach.

**Comment by antoniolg** [comment]
If you think it's going to simplify the code, then go ahead. But I wouldn't like to add much more complexity to the code (it is probably complex enough), because I want it to be understandable by the majority of devs that want to learn from it.

**Comment by antoniolg** [comment]
I'm closing this, feel free to reopen if you want to tackle this at some point.
