### ISSUE TITLE
build failed :BaseActivity.kt: (23, 27): Unresolved reference: find

### ISSUE THREAD

**Issue by IssacZhou777** [antoniolg/Bandhook-Kotlin#11]
I had added dependency as follow: 
     compile "org.jetbrains.anko:anko-sdk15:$ankoVersion"
    compile "org.jetbrains.anko:anko-support-v4:$ankoVersion"

now the ankoVersion is 0.8
but "org.jetbrains.anko.find" still can't found 
Can you help me? Thank you very much!

**Comment by antoniolg** [comment]
The app is not updated to final Kotlin version. Let me find some time to update it, and it should fix all your issues.

**Comment by IssacZhou777** [comment]
Thank you! I found that it is nothing about kotlin version but anko version, use the Anko library with version 0.8.2 is ok
