### ISSUE TITLE
Grade import error at the current state

### ISSUE THREAD

**Issue by rikutoe** [antoniolg/Bandhook-Kotlin#33]
Hi thank you for sharing this awesome project. 

Right now when I download and try to launch using the Android Studio 3.0 Canary version, I get the following error:

Error:Unable to find method 'com.android.build.gradle.internal.variant.BaseVariantData.getOutputs()Ljava/util/List;'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by vic-gonzi** [comment]
With current version (3.0 Beta 2) this issue doesn't appear.

As Android Studio 3.x is still under development, I'd not try to update current projects to it if it crashes. It's better to leave it for first stable version, IMHO.

**Comment by antoniolg** [comment]
@Etchee I'm closing this, if you confirm it keeps failing for you, feel free to reopen.
