### ISSUE TITLE
Kotlin src folder

### ISSUE THREAD

**Issue by tsuharesu** [antoniolg/Bandhook-Kotlin#4]
Just a tip: after M11 Kotlin will run fine on `src/main/java`, so you don't really need to add kotlin to main.java.srcDirs

http://blog.jetbrains.com/kotlin/2015/03/kotlin-m11-is-out/

You can close the issue after viewing the comment hehe

**Comment by antoniolg** [comment]
Thanks! I had it separated because I preferred not mixing files of both languages. But now that I can do everything using Kotlin, it'd make sense what you say. 

I'll do it when I find some minutes.
