### ISSUE TITLE
Move dependency injection to Dagger 2

### ISSUE THREAD

**Issue by antoniolg** [antoniolg/Bandhook-Kotlin#5]
Dagger 2 is supposed to be working on Kotlin, so it´s a good idea to try and move DI to that direction. Reasons:
- Current DI is supported by language, which is really good. But it´s a bit verbose and hard to maintain.
- Couldn´t find a way to make scoped injections, very useful for Android.
- The sole reason of learning Dagger 2 and see how it fits in a Kotlin project.

**Comment by Plastix** [comment]
Feel free to close this issue!

**Comment by altaf933** [comment]
It's already migrated into dagger-2 so why not close it ? Is that open to support **dagger-android-support**  as a enhancement ?

**Comment by antoniolg** [comment]
Yup, this needs to be closed. Thanks.
